### ISSUE TITLE
sprint: planning (initial)

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-oaiserver#23]
- [x] admin interface (#11 #22 @Dziolas)
  - [x] make sure that it works with example app (5) (@Dziolas, @jirikuncar)
  - [x] removal of "old" settings pages (3) (@jirikuncar)
- [x] docs
  - [x] setting up sets and data model (`_oai` field) (@jirikuncar)
    - [x] usage, API, TOC, style (5)
    - [x] skeleton - chapters (3) (later) later
    - [x] writing - data model, configuration (8-13) later
    - [x] marcxml -> marc21 (migration note)
  - [x] Invenio installation (docs, tests, deployment)
    - [x] invenio-base (cookiecutter base template) (5) (@hachreak)
    - [x] Invenio docs (config) (5) later (@hachreak @jirikuncar)
- [x] testing
  - [x] new set is added - check that records are updated (13) (@hachreak + @lnielsen #16 #10)
  - [x] MARC21, DC output format (5) (@jirikuncar)
  - [x] OAISet cache invalidation using redis + sha (@Dziolas @jirikuncar)
- [x] release on PyPI (3) (@jirikuncar)
  - [x] update POT
- [ ] ~~migration task from legacy~~ (not needed)
  - [ ] query migration
    - [ ] Zenodo/CDS dump of oaiset table (2) (@lnielsen @egabancho)
    - [ ] migration (5)
  - [x] populate metadata - record transformation (8) (@hachreak)
    - [x] tests: load invenio-records data and refactor tests a bit 
- [ ] deployment
  - [x] Demosite
    - [x] test conversion from MARC21 to Dublic Core (https://www.loc.gov/standards/marcxml/xslt/MARC21slim2OAIDC.xsl) (3-5) (@hachreak @jirikuncar #45)
    - [x] test conversion from MARC21 to Datacite (18 fields)
      - [x] define "Datacite JSON" (8) (@SamiHiltunen)
      - [x] "Datacite JSON" to XML + schema validation (5)
  - [ ] Zenodo (@lnielsen)
    - [x] fixture with dataset (3) (@lnielsen)
    - [x] custom DC output format (5)
      - [x] extract utility functions (?)
    - [ ] integration with communities (signal handler - after community created/deleted) (8)
      - [ ] addition of community creation signal https://github.com/inveniosoftware/invenio-communities/pull/17
  - [x] CDS labs https://github.com/CERNDocumentServer/cds/pull/82 (@jirikuncar)
  - [x] CERN Open Data portal (invenio3 branch)

--
@SamiHiltunen 3.5
@hachreak 6.5 (5.5)
@Dziolas 6.5
@lnielsen 5.5
@jirikuncar 7.5
@krzysztof (2.0)

(8 working days)

--
max. 106 points
29.5 man/day ~  (31.5)

**Comment by jirikuncar** [comment]
### Conclusion

- Time Estimates
  - training time needed + bootcamp (installation on developer machine)
  - review takes extra time
- ZenHub
  - slow :disappointed: and slower :cry: 
  - using pure GitHub and milestones 
- Documentation
  - creating examples
  - 20% of all estimates
- Deployment on services
  - check status first
